version: '3'


services:
  byte-barometer-backend-app:
    image: byte-barometer
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - ../.env
    environment:
      - ENV_VAR1=value1  # Add more environment variables as needed
    volumes:
      - .:/usr/src/app
      - ~/.cache/huggingface/transformers:/usr/src/app/.cache/huggingface/transformers
    ports:
      - "3000:3000"
