version: '3'

services:
  byte-barometer:
    image: byte-barometer 
    # entrypoint: python3 vector_manager.py populate -l 72000 -d 10000
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - ../.env
    environment:
      - ENABLE_GPU=True
    volumes:
      - .:/app
      - ~/.cache/huggingface/transformers:/app/.cache/huggingface/transformers
    ports:
      - "3000:3000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
                - utility # nvidia-smi
                - compute # CUDA
                - video   # NVDEC/NVENC/NVCUVID
    
