name: Build and test byte-barometer

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: false

      - name: Build frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: false

      - name: Build watchdog
        uses: docker/build-push-action@v5
        with:
          context: ./watchdog
          push: false
      