name: Build and deploy byte-barometer

# on:
#   push:
#     branches: ["main"]
# Temporary to test build and deploy
on:
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy backend
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.paperspace.com/v1/deployments"
          method: "POST"
          bearerToken: ${{ secrets.PAPERSPACE_API_KEY}}
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{ "apiVersion": "v0alpha0",  "enabled": false,  "env": [{"name": "HUGGINGFACE_API_KEY","value": "secret:HUGGINGFACE_API_KEY"},{"name": "OPENAI_API_KEY","value": "secret:OPENAI_API_KEY"},{"name": "PINECONE_API_KEY","value": "secret:PINECONE_API_KEY"},{"name": "PINECONE_ENVIRONMENT","value": "northamerica-northeast1-gcp"},{"name": "PINECONE_INDEX","value": "hackernews-embeddings"},{"name": "ENABLE_GPU","value": "True"}],"image": "stianlaa/byte-barometer:latest","name": "byte-barometer","port": 3000,"resources": {"instanceType": "P4000","replicas": 1}}'
