name: Build and deploy byte-barometer

# on:
#   push:
#     branches: ["main"]

# temporarily swapped to test deploy
on:
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set docker tag name
        run: echo "::set-output name=DOCKER_TAG_NAME::$(echo $GITHUB_REF | cut -d / -f 3 | sed 's/byte-barometer@//')"
        id: docker-tag-name

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            stianlaa/byte-barometer:${{ steps.docker-tag-name.outputs.DOCKER_TAG_NAME }}

      - name: Deploy Container
        uses: paperspace/deploy-action@v1.3
        with:
          apiKey: ${{ secrets.PAPERSPACE_API_KEY }}
          image: stianlaa/byte-barometer:${{ steps.docker-tag-name.outputs.DOCKER_TAG_NAME }}
          projectId: tszdixclcn
