name: Build and deploy byte-barometer

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            stianlaa/backend-byte-barometer:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            stianlaa/frontend-byte-barometer:latest

      - name: Build and push watchdog image
        uses: docker/build-push-action@v5
        with:
          context: ./watchdog
          push: true
          tags: |
            stianlaa/watchdog-byte-barometer:latest

      - name: Deploy frontend
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.digitalocean.com/v2/apps/bec6d6d2-e99d-4870-ae03-7522849849a5/deployments"
          method: "POST"
          bearerToken: ${{ secrets.DIGITAL_OCEAN_API_KEY}}
          customHeaders: '{"Content-Type": "application/json"}'

      - name: Deploy backend
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.paperspace.com/v1/deployments"
          method: "POST"
          bearerToken: ${{ secrets.PAPERSPACE_API_KEY}}
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{    "deploymentId": "ea647862-7e3f-46ec-b2ee-efe0e841eb8f",    "projectId": "plf3fs5whu1",    "config": {        "apiVersion": "v0alpha0",        "enabled": false,        "name": "byte-barometer",        "image": "stianlaa/backend-byte-barometer:latest",        "port": 3000,        "env": [            {                "name": "HUGGINGFACE_API_KEY",                "value": "secret:HUGGINGFACE_API_KEY"            },            {                "name": "OPENAI_API_KEY",                "value": "secret:OPENAI_API_KEY"            },            {                "name": "PINECONE_API_KEY",                "value": "secret:PINECONE_API_KEY"            },            {                "name": "PINECONE_ENVIRONMENT",                "value": "northamerica-northeast1-gcp"            },            {                "name": "PINECONE_INDEX",                "value": "hackernews-embeddings"            },            {                "name": "ENABLE_GPU",                "value": "True"            },            {                "name": "PAPERSPACE_API_KEY",                "value": "secret:PAPERSPACE_API_KEY"            },            {                "name": "SHUTDOWN_ON_TIMEOUT",                "value": "True"            }        ],        "resources": {            "replicas": 1,            "instanceType": "P4000"        }    }}'

      - name: Deploy watchdog
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.paperspace.com/v1/deployments"
          method: "POST"
          bearerToken: ${{ secrets.PAPERSPACE_API_KEY}}
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{    "deploymentId": "93c90d2d-8518-4abc-88b5-7517a180d6b8",    "projectId": "plf3fs5whu1",    "config": {        "apiVersion": "v0alpha0",        "enabled": true,        "name": "watchdog",        "image": "stianlaa/watchdog-byte-barometer:latest",        "port": 2999,        "env": [            {                "name": "PAPERSPACE_API_KEY",                "value": "secret:PAPERSPACE_API_KEY"            }        ],        "resources": {            "replicas": 1,            "instanceType": "C4"        }    }}'