name: Build and deploy byte-barometer

# on:
#   push:
#     branches: ["main"]
# Temporary to test build and deploy
on:
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            stianlaa/backend-byte-barometer:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            stianlaa/frontend-byte-barometer:latest

      - name: Deploy frontend
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.digitalocean.com/v2/apps/bec6d6d2-e99d-4870-ae03-7522849849a5/deployments"
          method: "POST"
          bearerToken: ${{ secrets.DIGITAL_OCEAN_API_KEY}}
          customHeaders: '{"Content-Type": "application/json"}'

      # Read JSON file content into an environment variable
      - name: Read JSON file
        id: read_json
        run: |
          echo "JSON_DATA<<EOF" >> $GITHUB_ENV
          cat frontend/paperspace.json >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Deploy backend
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.paperspace.com/v1/deployments"
          method: "POST"
          bearerToken: ${{ secrets.PAPERSPACE_API_KEY}}
          customHeaders: '{"Content-Type": "application/json"}'
          data: ${{ env.JSON_DATA }}
